name: Workflow
on: workflow_dispatch
jobs: 
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print to 
        run: echo Hello GIT
      - name: Print a few lines
        run: |
          echo First line
          echo Second line
