name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get repo
        uses: actions/checkout@v3
      - name: install
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: setup gardle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: build
        run: gradle build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get repo
        uses: actions/checkout@v3
      - name: install
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: setup gardle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - name: test
        run: gradle allureReport